
/* 
  Mountain View RV Park - Full Backend Initialization
*/

-- 1. BOOKINGS TABLE
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  rv_size TEXT DEFAULT 'standard',
  guests INTEGER DEFAULT 2,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Automated Confirmation Logic
-- This function acts as a stub for an Edge Function call (e.g., via pg_net extension)
CREATE OR REPLACE FUNCTION public.send_booking_confirmation()
RETURNS TRIGGER AS $$
BEGIN
  -- Logic to insert into a notifications table or call an external email API
  RAISE NOTICE 'Triggered confirmation for booking #% - Email: %', NEW.id, NEW.email;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_booking_created ON public.bookings;
CREATE TRIGGER on_booking_created
  AFTER INSERT ON public.bookings
  FOR EACH ROW
  EXECUTE FUNCTION public.send_booking_confirmation();

-- 2. GALLERY TABLE
CREATE TABLE IF NOT EXISTS public.gallery_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  title TEXT,
  category TEXT DEFAULT 'Scenery',
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;

-- Booking Policies
CREATE POLICY "Users can view their own bookings" ON public.bookings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own bookings" ON public.bookings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own bookings" ON public.bookings FOR DELETE USING (auth.uid() = user_id);

-- Gallery Policies
CREATE POLICY "Anyone can view gallery" ON public.gallery_images FOR SELECT USING (true);
CREATE POLICY "Auth users can post to gallery" ON public.gallery_images FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 4. VIEWS
-- Provides a clean source for the availability calendar without exposing user details
CREATE OR REPLACE VIEW public.global_availability AS
  SELECT check_in, check_out FROM public.bookings;
GRANT SELECT ON public.global_availability TO anon, authenticated;

-- 5. STORAGE BUCKET: 'gallery'
-- This block ensures the bucket exists and sets up public access rules
INSERT INTO storage.buckets (id, name, public) 
VALUES ('gallery', 'gallery', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS Policies
CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING (bucket_id = 'gallery');
CREATE POLICY "Authenticated Upload Access" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'gallery' AND auth.role() = 'authenticated');
CREATE POLICY "Owners can delete their uploads" ON storage.objects FOR DELETE USING (bucket_id = 'gallery' AND auth.uid()::text = (storage.foldername(name))[1]);
