
/* 
  Mountain View RV Park - Full Backend Initialization
  Updated with Automated Email Dispatch Logic
*/

-- 1. BOOKINGS TABLE
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  rv_size TEXT DEFAULT 'standard',
  guests INTEGER DEFAULT 2,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. NOTIFICATIONS TABLE (Audit Log for Email Dispatch)
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient TEXT NOT NULL,
  type TEXT NOT NULL,
  subject TEXT,
  content JSONB,
  status TEXT DEFAULT 'pending', -- 'pending', 'sent', 'failed'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. GALLERY TABLE
CREATE TABLE IF NOT EXISTS public.gallery_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  title TEXT,
  category TEXT DEFAULT 'Scenery',
  check_in DATE,
  check_out DATE,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. AUTOMATED NOTIFICATION LOGGING TRIGGER
-- This function logs a confirmation event. To actually trigger an email,
-- you should configure a "Database Webhook" in the Supabase Dashboard
-- that points to the 'booking-confirmation' Edge Function.
CREATE OR REPLACE FUNCTION public.log_booking_notification()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.notifications (recipient, type, subject, content, status)
  VALUES (
    NEW.email, 
    'booking_confirmation', 
    'Confirmed: Your Desert Outpost at Mountain View',
    jsonb_build_object(
      'booking_id', NEW.id,
      'guest_name', NEW.name,
      'arrival', NEW.check_in,
      'departure', NEW.check_out,
      'rv_size', NEW.rv_size,
      'guests', NEW.guests,
      'timestamp', NOW()
    ),
    'pending'
  );
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_booking_created_log ON public.bookings;
CREATE TRIGGER on_booking_created_log
  AFTER INSERT ON public.bookings
  FOR EACH ROW
  EXECUTE FUNCTION public.log_booking_notification();

-- 5. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Booking Policies
CREATE POLICY "Users can view their own bookings" ON public.bookings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own bookings" ON public.bookings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own bookings" ON public.bookings FOR DELETE USING (auth.uid() = user_id);

-- Gallery Policies
CREATE POLICY "Anyone can view gallery" ON public.gallery_images FOR SELECT USING (true);
CREATE POLICY "Auth users can post to gallery" ON public.gallery_images FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 6. AVAILABILITY VIEW
CREATE OR REPLACE VIEW public.global_availability AS
  SELECT check_in, check_out FROM public.bookings;
GRANT SELECT ON public.global_availability TO anon, authenticated;

-- 7. STORAGE BUCKET: 'gallery'
INSERT INTO storage.buckets (id, name, public) 
VALUES ('gallery', 'gallery', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Security
CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING (bucket_id = 'gallery');
CREATE POLICY "Authenticated Upload Access" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'gallery' AND auth.role() = 'authenticated');
CREATE POLICY "Owners can delete their uploads" ON storage.objects FOR DELETE USING (bucket_id = 'gallery' AND auth.uid()::text = (storage.foldername(name))[1]);

/*
  SETUP INSTRUCTIONS FOR REAL-TIME EMAILS:
  1. Deploy the 'booking-confirmation' Edge Function.
  2. Go to Supabase Dashboard -> Database -> Webhooks.
  3. Create a New Webhook:
     - Name: 'send-booking-email'
     - Table: 'public.bookings'
     - Events: 'INSERT'
     - Type: 'HTTP Request'
     - Method: 'POST'
     - URL: [Your Edge Function URL]
     - Auth: Add your Supabase Service Role Key as 'Bearer Token'.
*/
